name: FreqUI CI

on:
  push:
    branches:
      - main
      - ci/**
  pull_request:
    branches:
      - main
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        node: [ "18", "20", "21", "22"]

    steps:
    - uses: actions/checkout@v4


    - name: Install pnpm
      uses: pnpm/action-setup@v3

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        cache: 'pnpm'


    - run: pnpm install

    - name: Run Lint
      run: pnpm run lint-ci

    - name: Run type check
      run: pnpm run check-types

    - name: Run Tests
      run: pnpm run test:unit

    # Playwright section
    - name: Install Playwright Browsers
      run: pnpm run playwright install --with-deps

    - name: Run Playwright tests
      run: pnpm run playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-${{ matrix.node }}
        path: playwright-report/
        retention-days: 30

    # End Playwright section

    - name: Build build
      run: pnpm run build

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      # Ideally this would upload the zip file from below - but this action currently does not support this.
      with:
        name: freqUI-${{ matrix.node }}
        path: |
          dist
          !dist/**/*.map
        retention-days: 10

    - name: Zip files for release
      if: github.event_name == 'release' && matrix.node == '18'
      run: |
        cd dist/
        zip -r ../freqUI.zip .
        cd ../


    - name: Upload release binaries
      uses: alexellis/upload-assets@0.4.1
      if: github.event_name == 'release' && matrix.node == '18'
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./freqUI.zip"]'
