name: Build and Publish Docker Container

on:
  push:
    branches:
      - main
      - docker_container
  release:
    types: [published]
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    environment:
      name: Production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          freqtradeorg/frequi
          ghcr.io/freqtrade/frequi
        # generate Docker tags based on the following events/attributes
        tags: |
           type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
           type=semver,pattern={{version}}


    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
